name = "Origins 4"
author = "Us"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "901680e165ada1bd1fb81aeecf8eddcee53cb47916b3950fc96c9add5d8aab20"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
