name = "Origins 4"
author = "Us"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7411facff94ca98d5b24e664c9ff72262c4bb72c0e50dd9e5b17093465602ede"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
