name = "Origins 4"
author = "Us"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "151d6c3bdc5aa5710c6d08a708150cb4d3e27570dada013e8864d946d2b9f105"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
