name = "Origins 4"
author = "Us"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c85c956e2c4d1f2e5a0d2f8c9bb8bc58fffcfbc6a486c3c43a23020e69ac3791"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
