name = "Origins 4"
author = "Us"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b650915053dfa28d47cf41bc2e1163194f148f93200dc0ed37ba862981ec969"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
